# Generated by Django 3.2 on 2021-05-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Pages', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
            ],
        ),
    ]
